### ISSUE TITLE
a problem with patroni

### ISSUE THREAD

**Issue by mishgad** [ioguix/vagrant-patroni#1]
using ur cluster, how can i see status of a  patroni cluster?
![Снимок экрана от 2019-10-14 20-08-06](https://user-images.githubusercontent.com/37111002/66769671-5d6afb80-eebe-11e9-9f65-d94b1248c79c.png)

**Comment by ioguix** [comment]
Hello,

I hope you have been able to fix the issue on your side by the time...

As far as it could still interest you, I did fix things in the master branch.

Sorry for the delay anyway.
